name: CI-CD pipeline # isim vermek için kullanılır

on: 
  workflow_dispatch: # manuel çalıştırma
  schedule:
    - cron: "0 8 * * *" # her sabah 8'de çalışır 
  push: 
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Echo user login
        run: echo "Hello, ${{ github.actor }}"

  test: 
    runs-on: ubuntu-latest
    name: Cypress Test Job
    container:
      image: cypress/base:latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js  
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm install 
        working-directory: ./ders1/cypress/e2e/ders3/cypress/e2e
        
      - name: Run Cypress Tests
        run: npx cypress run 
        working-directory: ./ders1/cypress/e2e/ders3/cypress/e2e
        
      - name: Upload Cypress videos
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: cypress_videos
          path: cypress/videos/**/*.mp4  

      - name: Upload Cypress screenshots
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: cypress_screenshots
          path: cypress/screenshots/**/*.png 
   